// src/components/Navbar.vue
<template>
	<div class="navbar-fixed">
		<nav>
			<div class="nav-wrapper blue">
				<span class="brand-logo center">VeganFuel</span>
				<!-- <router-link v-if="this.$route.path !== '/'" class="back-icon left" to="/">
					<i class="fas fa-chevron-left" />
				</router-link> -->
			</div>
		</nav>
	</div>
</template>

<script>
export default {};
</script>

<style scoped>
.brand-logo img {
  width: 1.8em;
  height: 1.8em;
  padding-bottom: 2px;
  vertical-align: middle;
}

.brand-logo {
  font-family: "Pacifico", cursive;
}

.ios-icon {
  vertical-align: middle;
  margin-left: 0.5em;
  margin-right: 0.5em;
}

.android-icon {
  vertical-align: middle;
  margin-right: 0.5em;
}

.back-icon {
  vertical-align: middle;
  margin-left: 0.5em;
}
</style>

// src/Components/Navbar/Navbar.jsx
import React, { Component } from "react";
import { Link } from "react-router-dom";

import "./Navbar.css";

class Navbar extends Component {
  render() {
    return (
      <div className="navbar-fixed">
        <nav>
          <div className="nav-wrapper blue">
            <span className="brand-logo center">VeganFuel</span>
            <a
              className="ios-icon right"
              href="https://play.google.com/store/apps/details?id=andreygalchevski.veganfuel&hl=en"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i className="fab fa-google-play" />
            </a>
            <a
              className="android-icon right"
              href="https://itunes.apple.com/us/app/veganfuel/id1275882059?mt=8"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i className="fab fa-app-store-ios" />
            </a>
            <Link className="back-icon left" to="/">
              <i className="fas fa-chevron-left" />
            </Link>
          </div>
        </nav>
      </div>
    );
  }
}

export default Navbar;
